version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["./wait-for-it.sh", ":", "--", "flask", "run", "--host=0.0.0.0", "--port="]
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env
    ports:
      - :
    depends_on:
      - db
    links:
      - db:db
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - ./postgres/:/docker-entrypoint-initdb.d/
    env_file:
      - ./.env
    ports:
      - ":"
volumes:
  postgres_data:
