from enum import Enum

class SexEnum(Enum):
    Male = "M"
    Female = "F"

class AssignmentCodeEnum(Enum):
    inactive = "IN"
    pre_rasp = "PR"
    rasp_phase_1 = "R1"
    rasp_phase_2 = "R2"
    graduation = "GR"

class RankEnum(Enum):
    private = "PVT"
    private_2nd_class = "PV2"
    specialist = "SPC"
    corporal = "CPL"
    sergeant = "SGT"
    private_first_class = "PFC"

class SportsEnum(Enum):
    baseball = "BSB"
    basketball = "BB"
    cross_country = "CC"
    football = "FB"
    gymnastics_cheerleading = "GYM"
    hockey = "HKY"
    lacrosse = "LCR"
    soccer = "SCR"
    softball = "SFB"
    swimming_water_polo = "SWM"
    tennis = "TEN"
    track_field = "TRK"
    vollyball = "VLY"
    wrestling = "WRST"

class MosEnum(Enum):
    indirect_fire_infantryman = "11C"
    combat_engineer = "12B"
    horizontal_construction_engineer = "12N"
    carpentry_and_masonry_specialist = "12W"
    geospatial_engineer = "12Y"
    unmanned_aircraft_systems_repairer = "15E"
    unmanned_aircraft_systems_operator = "15W"
    electronic_warfare_specialist = "17E"
    special_forces_candidate = "18X"
    corporal_missile_repairman = "22C"
    automatic_data_link_repairman = "25B"
    integrated_data_link_repairman = "25C"
    cable_systems_installer_maintainer = "25L"
    multimedia_illustrator = "25M"
    nodal_network_systems_operator_maintainer = "25N"
    microwave_systems_operator_maintainer = "25P"
    multichannel_transmission_systems_operator_maintainer = "25Q"
    satellite_comm_systems_ops_maintainer = "25S"
    signal_support_systems_specialist = "25U"
    combat_documentation_production_specialist = "25V"
    army_paralegal_specialist = "27D"
    fixed_ciphony_repairer = "32F"
    intelligence_analyst = "35F"
    geospatial_intelligence_imagery_analyst = "35G"
    human_intelligence_collector = "35M"
    signals_intelligence_analyst = "35N"
    cryptologic_linguist = "35P"
    financial_management_technician = "36B"
    psychological_operations_specialist = "37F"
    human_resources_specialist = "42A"
    chaplain_assistant = "56M"
    preventive_medicine_specialist = "68S"
    combat_medic_specialist = "68W"
    army_mental_health_specialist = "68X"
    chemical_biological_radiological_nuclear_specialists = "74D"
    transportation_management_coordinator = "88N"
    ammunition_specialist = "89B"
    army_explosive_ordnance_disposal_specialist = "89D"
    wheeled_vehicle_mechanic = "91B"
    utilities_equipment_repairer = "91C"
    tactical_power_generation_specialist = "91D"
    allied_trade_specialist = "91E"
    small_arms_artillery_repairer = "91F"
    fire_control_repairer = "91G"
    quartermaster_and_chemical_equipment_repairer = "91J"
    stryker_systems_maintainer = "91S"
    automated_logistical_specialist = "92A"
    petroleum_supply_specialist = "92F"
    culinary_specialist = "92G"
    army_parachute_rigger = "92R"
    water_treatment_specialist = "92W"
    unit_supply_specialist = "92Y"
    radio_and_communications_security_repairer = "94E"
    computer_detection_systems_repairer = "94F"
    automatic_test_systems_operator_and_maintainer = "94Y"
    ninetyfifth = "95F"
    other = "OTR"
    cavalry_scourt = "19D"
    fire_support = "13F"
    motor_transport = "88M"
    infantry = "11B"

class AssessmentCodeEnum(Enum):
    apf_push_ups = "APFPS"
    apf_sit_ups = "APFSU"
    apf_2_mile_run = "APF2M"
    apf_pull_ups = "APFPL"
    land_nav_week_4 = "LAN01"
    land_nav_week_8 = "LAN02"
    march = "MARCH"
    peer_review = "REVPR"
    board_review = "REVBR"
    rft_push_ups = "RFTPS"
    rft_sit_ups = "RFTSU"
    rft_5_mile_run = "RFT5M"
    rft_5_mile_ruck = "RFT5R"
    rft_pull_ups = "RFTPL"
    ranger_physical_assessment_test = "RPATT"
    history_exam = "TSTHS"
    standard_exam = "TSTSD"
    rfr_written_exam = "TSTRF"

class EducationEnum(Enum):
    ged = "GED"
    high_school = "HS"
    two_yr_degree = "2YR"
    four_yr_degree = "4YR"
